//This program will generate a random number between 0 and 1000.
//The user will be asked to guess what the number is repeatedly until the correct
//answer is achieved.
import java.util.*;  //Needed for the Scanner and random classes

public class GuessNumber
{
   public static void main(String[] args)
   {
      int correctnumber;   //Will store the number generated by the random method
      int guess= -1;
      int counter = 0;
   
    //Create an object of the Random class
    Random random = new Random(); //Generate a random number from 0 to 999
    Scanner input = new Scanner(System.in);
   
    //Generate an integer
    correctnumber = random.nextInt(1001);
   
    while(guess != correctnumber)
    {
      System.out.println("Guess a number between 0 and 1000");
      guess = input.nextInt();
      
      if(guess < correctnumber)
      {
         System.out.println("Too Low, try Again\n");
      }
      
      else if(guess > correctnumber)
      {
         System.out.println("Too High, try Again\n");
      }
      counter++;
    } //end while loop
   
   // Tell user that he or she is correct
 //  if(guess == correctnumber)
      System.out.println("Congradulations, you guessed correctly\n");
      System.out.println("It took you " + counter + " guesses");
      
  }//end main()
}//end class GuessNumber